export const GAME_CONSTANTS = {
	PADDLE_HEIGHT_OFFSET: 0.15,
	PADDLE_WIDTH_OFFSET: 0.015,
	PADDLE_SPEED_OFFSET: 0.02,
	PADDLE_CENTER_OFFSET: 0.07,

	SCORE_FONT_SIZE_OFFSET: 0.07,

	CENTER_LINE_TOP_OFFSET: 0.05,
	CENTER_LINE_BOTTOM_OFFSET: 0.95,
	CENTER_LINE_DASH: [7, 15],
	CENTER_LINE_WIDTH_OFFSET: 0.01,

	BALL_HEIGHT_OFFSET: 0.025,

	UPDATE_RATE: 1000 / 30,

	BALL_COLOR: '#ff0000',
	PLAYER_1_PADDLE_COLOR: '#ffffff',
	PLAYER_2_PADDLE_COLOR: '#ffffff',
	CENTER_LINE_COLOR: '#ffffff',
	SCORE_COLOR: '#ffffff',
	SCORE_FONT: 'Arial',
}
